Algoritmo "calcDiasHorasMinutos"

Var

   idade,dias,horas,minutos: inteiro
   nome: caractere

Inicio

   escreval("digite seu nome:")
   leia(nome)

  escreval("digite sua idade:")
  leia(idade)

   dias <- idade * 365
   horas <- dias * 24
   minutos <- horas * 60

   escreval("Nome: ",nome)
   escreval("Dias: ",dias)
   escreval("Horas: ",horas)
   escreval("Minutos: ",minutos)



Fimalgoritmo