Algoritmo "tresParametros"

Var

  int1,int2: inteiro
  real1: real


  procedimento procparam(n1,n2:inteiro;r1:real)

  var

  inicio

    escreval(n1,"  ",n2,"  ", r1)
    escreval(n1*n2*r1)

  fimprocedimento



Inicio

  escreval("Digite um número inteiro")
  leia(int1)

  escreval("Digite outro número inteiro")
  leia(int2)
  
  escreval("Digite um número Real")
  leia(real1)


  procparam(int1,int2,real1)




Fimalgoritmo