Algoritmo "registroData"


tipo
data=registro
dia:inteiro
mes:inteiro
ano:inteiro
fimregistro


Var


dataNascimento:data


Inicio

escreval("Digite o seu dia de nascimento")
leia(dataNascimento.dia)

escreval("Digite o seu mês de nascimento")
leia(dataNascimento.mes)

escreval("Digite o seu ano de nascimento")
leia(dataNascimento.ano)


escreval(dataNascimento.dia," /",dataNascimento.mes," /",dataNascimento.ano)

         



Fimalgoritmo