Algoritmo "semnome"
//
//
//
Var

 num1,num2,soma: inteiro


 //valor: real
 //texto: caractere
 //verificacao: logico


Inicio

   //valor <- 20.55
   //texto <- "Este é um texto."
   //verificacao <- verdadeiro
   escreval("Digite o primeiro número")
   leia(num1)
   escreval("Digite o segundo número")
   leia(num2)

   soma <- num1 + num2
   
   escreva("Resultado: ",soma)







Fimalgoritmo